name: Flake8

on: [push, pull_request]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Install flake8
        run: pip install flake8
        
      - name: Flake8 action
        # You may pin to the exact commit or the version.
        uses: suo/flake8-github-action@v1
        with:
          # The name of the check to add annotations to.
          # Generally the same as the job that uses this action
          checkName: 'flake8_py3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}