name: Flake8

on: [push, pull_request]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Flake8 action
        # You may pin to the exact commit or the version.
        uses: suo/flake8-github-action@releases/v1
        with:
          # The name of the check to add annotations to.
          # Generally the same as the job that uses this action
          checkName: 'flake8_py3'
